Repository Caphyon/clang-power-tools, pull requests merged in 2019-11, with the labels that each got.

#699 Win10 toggle switch
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/AppResources.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/ToggleStyle.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: enhancement

#700 add on/off state for toggle switch state
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/ToggleStyle.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: enhancement

#704 Llvm custom uri
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LlvmConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LlvmController.cs
  ClangPowerTools/ClangPowerTools/MVVM/LlvmUri.cs
  ClangPowerTools/ClangPowerTools/MVVM/LlvmVersions.cs
Labels: bug

#708 Redesign settings input dialog
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/CommonSettingsFunctionality.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/InputDataModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/InputDataViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputDataView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputDataView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml
  ClangPowerTools/ClangPowerTools/Resources/AddInputHover.png
  ClangPowerTools/ClangPowerTools/Resources/AddInputIdle.png
  ClangPowerTools/ClangPowerTools/Resources/RemoveInputHover.png
  ClangPowerTools/ClangPowerTools/Resources/RemoveInputIdle.png
Labels: enhancement

#709 Select llvm after installation
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LlvmSettingsViewModel.cs
Labels: enhancement

#710 Change missing LLVM message
  ClangPowerTools/ClangPowerTools/Error/ErrorParserConstants.cs
Labels: enhancement

#711 Squiggles
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/Error/TaskErrorModelBuilder.cs
  ClangPowerTools/ClangPowerTools/Error/TaskErrorViewModel.cs
  ClangPowerTools/ClangPowerTools/Extensions/IntExtension.cs
  ClangPowerTools/ClangPowerTools/Helpers/JoinUtility.cs
  ClangPowerTools/ClangPowerTools/Helpers/ScriptGenerator.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LicenseViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputDataView.xaml
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTag.cs
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTaggerProvider.cs
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleViewModel.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/IgnoreCompileCommandTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/IgnoreFormatCommandTests.cs
Labels: new feature
