Repository Caphyon/clang-power-tools, pull requests merged in 2019-03, with the labels that each got.

#544 Tidy settings do not persist
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Options/HeaderFiltersValue.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangTidyOptionsView.cs
  ClangPowerTools/ClangPowerTools/SettingsProvider.cs
Labels: bug

#545 apply the fallbackstyle for clang format on save
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
Labels: bug

#553 Release v4.9
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  docs/CHANGELOG.md
Labels: release

#555 Fix deprecated ap is dependences
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/app.config
  ClangPowerTools/ClangPowerTools/packages.config
Labels: bug

#564 Export clang tidy config
  ClangPowerTools/ClangPowerTools/Clang Configs/TidyConfigFile.cs
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/Commands/CommandIds.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyConfigCommand.cs
  ClangPowerTools/ClangPowerTools/Options/View/WpfPropertyGrid/BorderedTextBoxBrowseFormat.xaml.cs
  ClangPowerTools/ClangPowerTools/Options/View/WpfPropertyGrid/BorderedTextBoxBrowseTidy.xaml.cs
  ClangPowerTools/ClangPowerTools/Options/View/WpfPropertyGrid/PropertyData.cs
  ClangPowerTools/ClangPowerTools/Options/View/WpfPropertyGrid/PropertyGridResources.xaml
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ConfigurationPage.cs
  ClangPowerTools/ClangPowerTools/XmlSerializer.cs
Labels: new feature

#570 rename the execute method
  ClangPowerTools/ClangPowerTools/Commands/TidyConfigCommand.cs
Labels: bug

#572 perform the active documents save on the main thred before compile an…
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/DocumentsHandler.cs
  ClangPowerTools/ClangPowerTools/packages.config
Labels: bug

#575 Release v4.10
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#576 Running a command from the toolbar is run on the other files
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandIds.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandUILocation.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/DocumentsHandler.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowConstants.cs
  ClangPowerTools/ClangPowerTools/Script/ItemRelatedScriptBuilder.cs
Labels: bug

#581 Set manifest version
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#582 Active window command issue
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
Labels: bug
