Repository Caphyon/clang-power-tools, pull requests merged in 2019-05, with the labels that each got.

#604 Stop command status fix
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/StopClang.cs
  ClangPowerTools/ClangPowerTools/Events/CloseDataStreamingEventArgs.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowBuilder.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowConstants.cs
Labels: bug

#606 Fix commands logging and warning messages
  ClangPowerTools/ClangPowerTools/Attributes/ClangCheckAttribute.cs
  ClangPowerTools/ClangPowerTools/Attributes/ClangFormatPathAttribute.cs
  ClangPowerTools/ClangPowerTools/Attributes/ClangTidyPathAttribute.cs
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/SettingsCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/StopCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyConfigCommand.cs
  ClangPowerTools/ClangPowerTools/Events/ActiveDocumentEventArgs.cs
  ClangPowerTools/ClangPowerTools/Export Config/TidyConfigFile.cs
  ClangPowerTools/ClangPowerTools/Extensions/StringExtension.cs
  ClangPowerTools/ClangPowerTools/Helpers/ActiveWindowProperties.cs
  ClangPowerTools/ClangPowerTools/Helpers/AutomationUtil.cs
  ClangPowerTools/ClangPowerTools/Helpers/PCHCleaner.cs
  ClangPowerTools/ClangPowerTools/Helpers/RunningDocTableEvents.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsPathBuilder.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/Helpers/Vsix.cs
  ClangPowerTools/ClangPowerTools/Items/CurrentProject.cs
  ClangPowerTools/ClangPowerTools/Items/CurrentProjectItem.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/Options/XmlSerializer.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowConstants.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/Script/ItemRelatedScriptBuilder.cs
Labels: bug

#608 Unit tests
  ClangPowerTools/ClangPowerTools.sln
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/BasicCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandIds.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/SettingsCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/StopCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyConfigCommand.cs
  ClangPowerTools/ClangPowerTools/Events/CleanErrorListEventArgs.cs
  ClangPowerTools/ClangPowerTools/Events/CloseDataConnectionEventArgs.cs
  ClangPowerTools/ClangPowerTools/Export Config/TidyConfigFile.cs
  ClangPowerTools/ClangPowerTools/Files Operations/FileOpener.cs
  ClangPowerTools/ClangPowerTools/Helpers/DocumentsHandler.cs
  ClangPowerTools/ClangPowerTools/Helpers/PackageUtility.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/Options/ClangFormatPathValue.cs
  ClangPowerTools/ClangPowerTools/Options/ClangTidyPathValue.cs
  ClangPowerTools/ClangPowerTools/Options/HeaderFiltersValue.cs
  ClangPowerTools/ClangPowerTools/Options/View/ClangFormatOptionsUserControl.xaml.cs
  ClangPowerTools/ClangPowerTools/Options/View/ClangTidyCustomChecksUserControl.xaml.cs
  ClangPowerTools/ClangPowerTools/Options/View/WpfPropertyGrid/BorderedTextBoxBrowseFormat.xaml.cs
  ClangPowerTools/ClangPowerTools/Options/View/WpfPropertyGrid/BorderedTextBoxBrowseTidy.xaml.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangFormatOptionsView.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangGeneralOptionsView.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangTidyCustomChecksOptionsView.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangTidyOptionsView.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangTidyPredefinedChecksOptionsView.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ConfigurationPage.cs
  ClangPowerTools/ClangPowerTools/Options/XmlSerializer.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowBuilder.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowConstants.cs
  ClangPowerTools/ClangPowerTools/Script/ClangTidyModeParametersFactory.cs
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
  ClangPowerTools/ClangPowerTools/Settings/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/Settings/SettingsPathBuilder.cs
  ClangPowerTools/ClangPowerTools/Settings/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/UnitTestUtility/CommandTestUtility.cs
  ClangPowerTools/ClangPowerTools/UnitTestUtility/SettingsTestUtility.cs
  ClangPowerTools/ClangPowerTools/UnitTestUtility/UnitTestUtility.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/IgnoreCompileCommandTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/IgnoreFormatCommandTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/ScriptTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangPowerToolsUnitTests.csproj
  ClangPowerTools/ClangPowerToolsUnitTests/Constants/IgnoreCommand.cs
  ClangPowerTools/ClangPowerToolsUnitTests/PackageTests/AsyncPackageTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/FormatSettingsTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/GeneralSettingsTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/TidyCustomCheckesTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/TidyPredefinedChecksTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/TidySettingsTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/VSVersionTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/VsServiceProviderTests.cs
Labels: test

#610 Release v4.10.4
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#615 Issue when runing Format on selected items
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/BasicCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandUILocation.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Events/ActiveDocumentEventArgs.cs
  ClangPowerTools/ClangPowerTools/Events/CloseDataStreamingEventArgs.cs
  ClangPowerTools/ClangPowerTools/Helpers/DocumentsHandler.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/Options/Model/DefaultOptions.cs
  ClangPowerTools/ClangPowerTools/Options/ViewModel/ClangGeneralOptionsView.cs
  ClangPowerTools/ClangPowerTools/UnitTestUtility/SettingsTestUtility.cs
Labels: bug

#616 Fix include order of project directories
  ClangPowerTools/ClangPowerTools/psClang/msbuild-project-data.ps1
Labels: bug

#617 Release v4.10.5
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
