Repository Caphyon/clang-power-tools, pull requests merged in 2019-02, with the labels that each got.

#511 fix the hey not found unhandled exception
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
Labels: bug

#515 disable the open file mechanism on clang tidy-fix mode
  ClangPowerTools/ClangPowerTools/Files Operations/FileOpener.cs
Labels: bug

#517 Fix output pane switch for clang compile after msvc compile
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/SettingsCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/StopClang.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
Labels: bug

#519 Vs2019 support
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: enhancement

#520 User settings are lost when vs is closed
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandsController.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Script/ClangTidyModeParametersFactory.cs
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
  ClangPowerTools/ClangPowerTools/SettingsProvider.cs
Labels: bug

#521 save all dirty projects and not entire solution when a clang complile…
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Files Operations/FileOpener.cs
Labels: bug

#522 Command shortcuts
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
Labels: enhancement

#527 Release v4.8.1
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  docs/CHANGELOG.md
  docs/README.md
Labels: release
