Repository Caphyon/clang-power-tools, pull requests merged in 2019-09, with the labels that each got.

#660 CMake support
  ClangPowerTools/ClangPowerTools/CMake/CMakeBuilder.cs
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandUILocation.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Files Operations/FilePathCollector.cs
  ClangPowerTools/ClangPowerTools/Helpers/DocumentHandler.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/Items/CurrentDocument.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/Options/ClangTidyPathValue.cs
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
  ClangPowerTools/ClangPowerTools/Script/ItemRelatedScriptBuilder.cs
Labels: new feature

#661 Release notes upgrade window
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml.cs
  ClangPowerTools/ClangPowerTools/Resources/AlphabeticalIcon.PNG
  ClangPowerTools/ClangPowerTools/Resources/CPTLogo.png
  ClangPowerTools/ClangPowerTools/Resources/CategorizedIcon.PNG
  ClangPowerTools/ClangPowerTools/Resources/LogoCPT.png
  ClangPowerTools/ClangPowerTools/Resources/Logout.png
  ClangPowerTools/ClangPowerTools/Resources/ReleaseNotesBackground.png
Labels: enhancement

#662 Release v5.1
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#667 Improve ignore commands
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/PropertyHandler.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
Labels: enhancement

#668 Disable cpt when there is no cpp selected
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/Script/ScriptConstants.cs
Labels: enhancement

#670 Encoding converter
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandIds.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Error/ErrorDetector.cs
  ClangPowerTools/ClangPowerTools/Events/HasEncodingErrorEventArgs.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/MVVM/Command/RelayCommand.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/FileModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/EncodingErrorViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/EncodingErrorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/EncodingErrorView.xaml.cs
  ClangPowerTools/ClangPowerTools/Output/OutputContentModel.cs
  ClangPowerTools/ClangPowerTools/Output/OutputProcessor.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/Properties/Resources.Designer.cs
  ClangPowerTools/ClangPowerTools/Properties/Resources.resx
  ClangPowerTools/ClangPowerTools/Resources/BannersError.png
  ClangPowerTools/ClangPowerTools/Resources/ClangPowerToolsIco.ico
  ClangPowerTools/ClangPowerTools/Resources/EncodingConverter.ico
  ClangPowerTools/ClangPowerTools/Resources/iconError.png
  ClangPowerTools/ClangPowerTools/packages.config
Labels: new feature

#671 Inlude cpt icon in all windows
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/Resources/Icon.png
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: enhancement

#672 Refactor settings
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Export Config/TidyConfigFile.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsViewModelProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SearchBoxView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/Script/ClangTidyModeParametersFactory.cs
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
Labels: enhancement

#674 remove ok button
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
Labels: enhancement

#677 Fix unit tests
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/UnitTestUtility/SettingsTestUtility.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/IgnoreCompileCommandTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/IgnoreFormatCommandTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/ClangCommandTests/ScriptTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/CompilerSettingsTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/FormatSettingsTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/GeneralSettingsTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/TidyCustomCheckesTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/TidyPredefinedChecksTests.cs
  ClangPowerTools/ClangPowerToolsUnitTests/Settings Tests/TidySettingsTests.cs
Labels: bug

#673 Free trial support
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Helpers/RegistryUtility.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FreeTrialController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LicenseController.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/GeneralSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LicenseViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LoginViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/ReleaseNotesViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LicenseView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/LicenseView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml.cs
  ClangPowerTools/ClangPowerTools/Resources/CPTLogoManageExtensionVS.png
  ClangPowerTools/ClangPowerTools/Resources/EncodingConverter.ico
  ClangPowerTools/ClangPowerTools/Resources/iconCommercial.png
  ClangPowerTools/ClangPowerTools/Resources/iconFreeTrial.png
  ClangPowerTools/ClangPowerTools/Resources/iconPersonal.png
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: enhancement

#679 Fix sign up
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LoginViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml
Labels: bug

#680 Release v5.2.1
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#682 Fix predefined checks
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/CompilerSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/GeneralSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SearchBoxView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SearchBoxView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml.cs
Labels: bug
