Repository Caphyon/clang-power-tools, pull requests merged in 2019-07, with the labels that each got.

#628 Release v5.0
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#632 Email password validation
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LoginViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/LoginView.xaml.cs
Labels: enhancement

#634 Release v5.0.1
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#639 Fix warnings
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/Logout.cs
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/Extensions/TaskExtensions.cs
  ClangPowerTools/ClangPowerTools/Helpers/DispatcherHandler.cs
  ClangPowerTools/ClangPowerTools/Helpers/StatusBarHandler.cs
  ClangPowerTools/ClangPowerTools/Helpers/UIUpdater.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/LicenseModel.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/app.config
  ClangPowerTools/ClangPowerTools/packages.config
  ClangPowerTools/ClangPowerToolsUnitTests/ClangPowerToolsUnitTests.csproj
  ClangPowerTools/ClangPowerToolsUnitTests/PackageTests/AsyncPackageTests.cs
Labels: bug
