Repository Caphyon/clang-power-tools, pull requests merged in 2019-12, with the labels that each got.

#714 make squiggles purple
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
Labels: enhancement

#716 Release v5.4
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/InputDataViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#717 enable clang format validation on any command trigger source
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
Labels: bug

#719 Optionally show error list
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/CompilerSettingsModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsTooltips.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: enhancement

#723 Resizable LLVM window
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml
Labels: bug

#725 Fix file format
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Events/FormatCommandEventArgs.cs
  ClangPowerTools/ClangPowerTools/Helpers/FileSystem.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LlvmController.cs
Labels: bug

#726 Release v5.5
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
