Repository Caphyon/clang-power-tools, pull requests merged in 2020-03, with the labels that each got.

#754 Custom clang-tidy not working because of absolute path containing spaces
  ClangPowerTools/ClangPowerTools/clang-build.ps1
  ClangPowerTools/ClangPowerTools/psClang/io.ps1
  ClangPowerTools/ClangPowerTools/psClang/io.tests.ps1
Labels: bug

#761 Clang runs on other project types
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
Labels: bug

#763 Release v5.6.1
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/BackgroundTidy.cs
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/DataProcessor.cs
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/PowerShellWrapperBackground.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/Script/PowerShellWrapper.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#766 fix background clang tidy on external dependency file
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/BackgroundTidy.cs
Labels: bug

#767 .clang-tidy file confirmation after export configuration
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
Labels: bug

#768 Release v5.6.2
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#770 Fix prop sheet directory location prop backup and restore mechanism, …
  ClangPowerTools/ClangPowerTools/psClang/msbuild-project-load.ps1
Labels: bug

#772 Release v5.6.3
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#774 Release v5.6.4
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/BackgroundTidy.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#777 LLVM 10 support
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LLVMVersionsAlternate.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LlvmVersions.cs
Labels: feature

#781 Release v5.7
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LoginViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
