Repository Caphyon/clang-power-tools, pull requests merged in 2020-06, with the labels that each got.

#828 Clang format for file without project
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/Services/VsServiceProvider.cs
Labels: enhancement

#831 Release v6.0
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#834 Release v6.0.1
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#838 Fix focus lost by keeping focus on active document
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/Helpers/DocumentHandler.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
Labels: bug

#841 Support for clang format file config
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/FileSystem.cs
Labels: bug

#842 Add support for project definitions using environment variables in SLN
  ClangPowerTools/ClangPowerTools/clang-build.ps1
Labels: bug

#844 clear output window after clang-format missing config file error
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
Labels: bug

#845 Multiple tidy checks selection
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml.cs
Labels: enhancement

#846 Tooltip on entire row
  ClangPowerTools/ClangPowerTools/MVVM/SettingsTooltips.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: bug

#848 Fix dropdown size
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/AppResources.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/SettingsComboBoxStyle.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: bug

#849 Bugfix reset settings
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Interfaces/IView.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/GeneralSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml.cs
Labels: bug

#852 Tutorial reference
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatEditorViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml.cs
Labels: enhancement

#853 disable all the Clang Tidy default checks when .clang-tidy file is exported
  ClangPowerTools/ClangPowerTools/Export Config/TidyConfigFile.cs
Labels: bug

#854 Team tab
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/ApiUtility.cs
  ClangPowerTools/ClangPowerTools/Helpers/NetworkUtility.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsApi.cs
  ClangPowerTools/ClangPowerTools/MVVM/Interfaces/ILicense.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/CommercialLicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LocalLicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/PersonalLicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/Token.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/InputMultipleDataViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TeamSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TeamSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TeamSettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/WebApi/WebApiUrl.cs
Labels: feature

#855 Team tab style and refactor
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Helpers/SettingsApi.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TeamSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TeamSettingsView.xaml
  ClangPowerTools/ClangPowerTools/Resources/TeamIcon.png
Labels: feature
