Repository Caphyon/clang-power-tools, pull requests merged in 2020-11, with the labels that each got.

#893 Remove license type requirement
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/AccountViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TeamSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml
Labels: enhancement

#894 Release v6.4.2
  ClangPowerTools/ClangPowerTools/MVVM/Models/AccountModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/AccountViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#897 Fix local llvm detection
  ClangPowerTools/ClangPowerTools/MVVM/PreinstalledLlvm.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsTooltips.cs
Labels: bug

#899 Account UI improvements
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/AccountViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TeamSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml
Labels: enhancement

#901 Handle temporary file from vsix
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/StopCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/ClangTidyCleaner.cs
Labels: bug

#902 Custom llvm path
  ClangPowerTools/ClangPowerTools/MVVM/CommonSettingsFunctionality.cs
  ClangPowerTools/ClangPowerTools/MVVM/PreinstalledLlvm.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LlvmSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml.cs
Labels: enhancement

#903 Feedback tab
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FeedbackViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FeedbackView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FeedbackView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/ImageResources.xaml
  ClangPowerTools/ClangPowerTools/Resources/FeedbackIcon.png
  ClangPowerTools/ClangPowerTools/Resources/GitHubMark.png
Labels: enhancement

#904 Cmake beta version warning
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Helpers/RegistryUtility.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FreeTrialController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CMakeBetaWarning.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CMakeBetaWarning.xaml
Labels: enhancement

#905 Release v6.5
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
