Repository Caphyon/clang-power-tools, pull requests merged in 2020-07, with the labels that each got.

#857 Microsoft format option
  ClangPowerTools/ClangPowerTools/MVVM/Constants/ComboBoxConstants.cs
Labels: enhancement

#859 Account view
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsApi.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LicenseController.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseInfo.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseType.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/AccountModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/AccoutApiModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/OldSettings/OldModels/DefaultOptions.cs
  ClangPowerTools/ClangPowerTools/MVVM/Provider/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/AccountViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TeamSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/AppResources.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/SettingsButtonStyle.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TeamSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/WebApi/WebApiUrl.cs
  ClangPowerTools/ClangPowerTools/Resources/AccountAvatarIcon.png
  ClangPowerTools/ClangPowerTools/Resources/AccountIcon.png
  ClangPowerTools/ClangPowerTools/Resources/ClangSplitBackground.png
  ClangPowerTools/ClangPowerTools/Resources/CloudIcon.png
  ClangPowerTools/ClangPowerTools/Resources/LogoutIcon.png
  ClangPowerTools/ClangPowerTools/Resources/SettingsBackground.png
  ClangPowerTools/ClangPowerTools/Resources/StorageIcon.png
  ClangPowerTools/ClangPowerTools/Script/ScriptConstants.cs
Labels: feature

#860 Fix account tab for trial
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Models/AccountApiModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/AccoutApiModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LicenseViewModel.cs
Labels: bug

#861 align license and version with the corresponding labels
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml
Labels: bug

#862 Change license acording with account after login
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LoginViewModel.cs
Labels: bug

#863 Fix license expiration date empty state
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FreeTrialController.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LicenseViewModel.cs
Labels: bug

#864 Refactor license check for command controller
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Events/LicenseEventArgs.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsApi.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LicenseState.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LicenseType.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/AccountController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LicenseController.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseInfo.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseType.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LoginViewModel.cs
Labels: bug

#865 Account tab bugfixes
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/AccountViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml
Labels: bug

#866 Format on save docCookie
  ClangPowerTools/ClangPowerTools/Helpers/RunningDocTableEvents.cs
Labels: bug

#868 Release v6.1
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TeamSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#869 Diff design
  ClangPowerTools/ClangPowerTools/Compare/DiffMatchPatch.cs
  ClangPowerTools/ClangPowerTools/Extensions/StringExtension.cs
Labels: enhancement
