Repository Caphyon/clang-power-tools, pull requests merged in 2020-01, with the labels that each got.

#728 License cost
  ClangPowerTools/ClangPowerTools/MVVM/Views/LicenseView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TrialExpiredView.xaml
Labels: bug

#729 Running commands on files outside solution
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/Items/ItemsCollector.cs
  ClangPowerTools/ClangPowerTools/Script/ScriptConstants.cs
Labels: bug

#730 Cannot add file to ignore format
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
Labels: bug

#732 Format on save error when config file is missing
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Helpers/RunningDocTableEvents.cs
Labels: bug

#733 Settings support upgrade footer
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/SettingsCommand.cs
  ClangPowerTools/ClangPowerTools/Events/LicenseEventArgs.cs
  ClangPowerTools/ClangPowerTools/Helpers/RegistryUtility.cs
  ClangPowerTools/ClangPowerTools/Helpers/SettingsPathBuilder.cs
  ClangPowerTools/ClangPowerTools/Helpers/SolutionInfo.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/AccountController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FreeTrialController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LicenseController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Interfaces/IAccountValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/Interfaces/ILicense.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/CommercialLicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseInfo.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseState.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseType.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LocalLicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/PersonalLicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/GeneralSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LicenseViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/ReleaseNotesViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/Components/BuyNowFooter.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Components/BuyNowFooter.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/AppResources.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/YellowButtonStyle.xaml
Labels: enhancement

#735 Release v5.5.1
  ClangPowerTools/ClangPowerTools/Error/ErrorParserConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#736 Feedback for ignored files
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Events/FormatCommandEventArgs.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/CompilerSettingsViewModel.cs
Labels: bug

#738 keep focus in the editor after clang format
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
Labels: bug

#739 Release v5.5.2
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/Events/CleanErrorListEventArgs.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#741 fix squiggles line and column random change
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
Labels: bug
