Repository Caphyon/clang-power-tools, pull requests merged in 2020-10, with the labels that each got.

#881 Redesign file selection
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Models/InputDataModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/SelectedFileModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/DetectStyleFileSelectorViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/InputDataViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/Components/InputList.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Components/InputList.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/DetectFormatStyleMenuView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/DetectFormatStyleMenuView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/DetectStyleFileSelectorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/DetectStyleFileSelectorView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FileSizeWarningView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputDataView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/SettingsButtonStyle.xaml
Labels: enhancement

#883 Release v6.3
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#885 LLVM 11
  ClangPowerTools/ClangPowerTools/MVVM/CommonFormatEditorFunctionality.cs
  ClangPowerTools/ClangPowerTools/MVVM/CommonSettingsFunctionality.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LLVMVersionsAlternate.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LlvmVersions.cs
  ClangPowerTools/ClangPowerTools/llvm/bin/clang-format.exe
Labels: enhancement

#886 Bugfix/879 too long cmdline
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
  ClangPowerTools/ClangPowerTools/clang-build.ps1
Labels: bug

#887 Release v6.4
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#890 Fix tidy parameters creation
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
Labels: bug

#891 Release v6.4.1
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
