Repository Caphyon/clang-power-tools, pull requests merged in 2020-02, with the labels that each got.

#742 Llvm 9.0.1
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LLVMVersionsAlternate.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LlvmVersions.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LlvmController.cs
Labels: enhancement

#743 Release v5.5.3
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#748 Create clang format style editor
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Export Config/FormatOptionFile.cs
  ClangPowerTools/ClangPowerTools/Extensions/StringExtension.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/CPPKeywords.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/ComboBoxConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LicenseState.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LicenseType.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData.cs
  ClangPowerTools/ClangPowerTools/MVVM/Interfaces/IFormatOption.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseInfo.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/FormatOptionInputModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/FormatOptionModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/FormatOptionToggleModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/OldSettings/OldModels/DefaultOptions.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsTooltips.cs
  ClangPowerTools/ClangPowerTools/MVVM/TextManipulation.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatStyleViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatStyleView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatStyleView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputDataView.xaml
  ClangPowerTools/ClangPowerTools/Resources/Input.png
  ClangPowerTools/ClangPowerTools/Resources/Output.png
Labels: feature

#749 Stop command kill process fix
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/CompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/StopCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/MVVM/Interfaces/IFormatOption.cs
  ClangPowerTools/ClangPowerTools/MVVM/TextManipulation.cs
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/Script/PowerShellWrapper.cs
  ClangPowerTools/ClangPowerTools/Script/RunningProcesses.cs
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
Labels: bug
