Repository Caphyon/clang-power-tools, pull requests merged in 2020-04, with the labels that each got.

#783 Predefined styles for Clang-Format editor
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Export Config/ClangFormatFile.cs
  ClangPowerTools/ClangPowerTools/Export Config/FormatOptionFile.cs
  ClangPowerTools/ClangPowerTools/Helpers/FileSystem.cs
  ClangPowerTools/ClangPowerTools/MVVM/CommonSettingsFunctionality.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/ComboBoxConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FormatEditorController.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData/FormatOptionsChromiumData.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData/FormatOptionsData.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData/FormatOptionsGoogleData.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData/FormatOptionsMicrosoftData.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData/FormatOptionsMozillaData.cs
  ClangPowerTools/ClangPowerTools/MVVM/FormatOptionsData/FormatOptionsWebKitData.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/FormatOptionModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/FormatOptionMultipleInputModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Provider/FormatOptionsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/Provider/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatEditorViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatStyleViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/InputMultipleDataViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatStyleView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputDataView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputMultipleDataView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/InputMultipleDataView.xaml.cs
Labels: feature

#784 Drag and drop file format editor
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatEditorViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatStyleViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatStyleView.xaml.cs
  ClangPowerTools/ClangPowerTools/Script/ScriptConstants.cs
Labels: enhancement

#785 fix spanTag overflow
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
Labels: bug

#786 Detect preinstalled LLVM
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/BackgroundTidy.cs
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/PowerShellWrapperBackground.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreCompileCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/IgnoreFormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Convertors/ClangGeneralAdditionalIncludesConvertor.cs
  ClangPowerTools/ClangPowerTools/Error/ErrorWindowController.cs
  ClangPowerTools/ClangPowerTools/Export Config/TidyConfigFile.cs
  ClangPowerTools/ClangPowerTools/Helpers/FileSystem.cs
  ClangPowerTools/ClangPowerTools/Helpers/RegistryUtility.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FreeTrialController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/LlvmController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/CompilerSettingsModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/LlvmModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/LlvmSettingsModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Provider/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/CompilerSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/GeneralSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/InputMultipleDataViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LlvmSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/LlvmSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml.cs
  ClangPowerTools/ClangPowerTools/Script/ClangTidyModeParametersFactory.cs
  ClangPowerTools/ClangPowerTools/Script/GenericScriptBuilder.cs
  ClangPowerTools/ClangPowerTools/Script/PowerShellWrapper.cs
  ClangPowerTools/ClangPowerTools/Squiggle/SquiggleErrorTagger.cs
Labels: enhancement

#787 Bug-fix LLVM selection
  ClangPowerTools/ClangPowerTools/Helpers/RegistryUtility.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LlvmSettingsViewModel.cs
Labels: bug

#788 stop all the backgound runners when a VS build/compile starts
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
Labels: bug

#794 Release v5.8
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/BackgroundTidy/PowerShellWrapperBackground.cs
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/StopCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/RegistryUtility.cs
  ClangPowerTools/ClangPowerTools/MVVM/LicenseValidation/LicenseValidator.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/LlvmModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/PreinstalledLlvm.cs
  ClangPowerTools/ClangPowerTools/MVVM/Provider/SettingsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LicenseViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/LlvmSettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml.cs
  ClangPowerTools/ClangPowerTools/Script/PowerShellWrapper.cs
  ClangPowerTools/ClangPowerTools/Script/RunningProcesses.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#795 Fix command on ignore file message
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
Labels: bug

#796 Feedback clang format on ignored files
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerToolsPackage.cs
  ClangPowerTools/ClangPowerTools/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/IgnoreActions/IgnoreItem.cs
  ClangPowerTools/ClangPowerTools/Items/IItem.cs
Labels: enhancement

#797 show export confirmation only if the OK button was pressed
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
Labels: bug
