Repository Caphyon/clang-power-tools, pull requests merged in 2020-05, with the labels that each got.

#798 Missing LLVM doesn't display correct output message
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
Labels: bug

#799 Missing LLVM doesn't display correct output message
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
Labels: bug

#803 Release v5.9
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/Commands/CommandController.cs
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Events/FormatCommandEventArgs.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#806 Settings crash
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
Labels: bug

#807 Release v5.9.1
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#808 Predefined tidy checks bug
  ClangPowerTools/ClangPowerTools/Error/ErrorParserConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsHandler.cs
Labels: bug

#809 Release v5.9.2
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#811 Tidy checks select all
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Events/BoolEventArgs.cs
  ClangPowerTools/ClangPowerTools/MVVM/CollectionElementsCounter.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/TidyCheckModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidyChecksViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/ToggleStyle.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: enhancement

#814 Show output window switch
  ClangPowerTools/ClangPowerTools/MVVM/Models/CompilerSettingsModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsTooltips.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/GeneralSettingsView.xaml
  ClangPowerTools/ClangPowerTools/Output/OutputWindowController.cs
Labels: enhancement

#815 Auto detect clang tidy config
  ClangPowerTools/ClangPowerTools/Commands/FormatCommand.cs
  ClangPowerTools/ClangPowerTools/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerTools/Helpers/FileSystem.cs
  ClangPowerTools/ClangPowerTools/MVVM/Models/TidySettingsModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/SettingsTooltips.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
Labels: enhancement

#824 Search for Format Editor
  ClangPowerTools/ClangPowerTools/MVVM/Provider/FormatOptionsProvider.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatEditorViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorView.xaml.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/SearchBoxView.xaml
Labels: feature

#826 Disable select predefined checks
  ClangPowerTools/ClangPowerTools/MVVM/Views/Styles/SettingsButtonStyle.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidySettingsView.xaml.cs
Labels: bug

#827 Tidy file missing flags
  ClangPowerTools/ClangPowerTools/Export Config/TidyConfigFile.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/TidyChecksView.xaml
Labels: bug
