Repository Caphyon/clang-power-tools, pull requests merged in 2021-02, with the labels that each got.

#918 change the size of the settings window
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
Labels: bug

#919 Editor fixes
  ClangPowerTools/ClangPowerTools/MVVM/Constants/FormatEditorConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorWarning.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatEditorWarning.xaml.cs
Labels: bug

#920 Release v7.0
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#922 Handle account details visibility
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/AccountViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/AccountView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/Resources/LICENSE.txt
Labels: enhancement

#924 Release v7.0.1
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/Executables/ClangFormatEditor.exe
  ClangPowerTools/ClangPowerTools/Executables/ClangFormatEditor.pdb
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#927 fix settings crash when the installed LLVM version is not present in …
  ClangPowerTools/ClangPowerTools/MVVM/PreinstalledLlvm.cs
Labels: bug

#928 Fix format editor
  ClangPowerTools/ClangPowerTools/Executables/ClangFormatEditor.exe
  ClangPowerTools/ClangPowerTools/MVVM/Constants/FormatEditorConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FormatEditorController.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/FormatSettingsViewModel.cs
Labels: bug

#929 Update footer
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/Components/BuyNowFooter.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/SettingsView.xaml
Labels: enhancement

#930 Release v7.1
  ClangPowerTools/ClangPowerTools/Executables/ClangFormatEditor.exe
  ClangPowerTools/ClangPowerTools/MVVM/Constants/FormatEditorConstants.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LLVMVersionsAlternate.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LlvmVersions.cs
  ClangPowerTools/ClangPowerTools/MVVM/Controllers/FormatEditorController.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
