Repository Caphyon/clang-power-tools, pull requests merged in 2021-03, with the labels that each got.

#938 Format Editor installer projects
  ClangPowerTools/ClangFormatEditorInstaller/Clang Format Editor Updates.aip
  ClangPowerTools/ClangFormatEditorInstaller/Clang Format Editor.aip
Labels: feature

#940 enable clang-format action for .inl files
  ClangPowerTools/ClangPowerTools/Script/ScriptConstants.cs
Labels: bug

#941 fix footer display
  ClangPowerTools/ClangPowerTools/Commands/SettingsCommand.cs
  ClangPowerTools/ClangPowerTools/MVVM/ViewModels/SettingsViewModel.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/Components/BuyNowFooter.xaml
Labels: bug

#942 use just '\' character in the file paths for consistency
  ClangPowerTools/ClangPowerTools/Error/TaskErrorModelBuilder.cs
Labels: bug

#943 Release v7.2
  ClangPowerTools/ClangFormatEditorInstaller/Clang Format Editor Updates.aip
  ClangPowerTools/ClangFormatEditorInstaller/Clang Format Editor.aip
  ClangPowerTools/ClangPowerTools/Executables/ClangFormatEditor.exe
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LLVMVersionsAlternate.cs
  ClangPowerTools/ClangPowerTools/MVVM/Constants/LlvmVersions.cs
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#946 Release v7.2.1
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release

#949 Release v7.3
  ClangPowerTools/ClangFormatEditorInstaller/Clang Format Editor Updates.aip
  ClangPowerTools/ClangFormatEditorInstaller/Clang Format Editor.aip
  ClangPowerTools/ClangPowerTools/Executables/ClangFormatEditor.exe
  ClangPowerTools/ClangPowerTools/MVVM/Views/CompilerSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/FormatSettingsView.xaml
  ClangPowerTools/ClangPowerTools/MVVM/Views/ReleaseNotesView.xaml
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
Labels: release
