Repository Caphyon/clang-power-tools, pull requests merged in 2022-05, with the labels that each got.

#1111 Implement Generate Documentation command
  ClangPowerTools/ClangPowerTools.aip
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  ClangPowerTools/ClangPowerToolsShared/ClangPowerToolsPackageImpl.cs
  ClangPowerTools/ClangPowerToolsShared/ClangPowerToolsShared.projitems
  ClangPowerTools/ClangPowerToolsShared/Commands/ClangCommand.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/CommandController.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/CommandIds.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/DocumentationHtmlCommand.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/DocumentationMdCommand.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/DocumentationYamlCommand.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/JsonCompilationDatabaseCommand.cs
  ClangPowerTools/ClangPowerToolsShared/Helpers/GenerateDocumentation.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/Constants/PathConstants.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/Controllers/TidyToolWindowController.cs
  ClangPowerTools/ClangPowerToolsShared/Output/OutputWindowConstants.cs
  ClangPowerTools/ClangPowerToolsShared/Output/OutputWindowController.cs
  ClangPowerTools/ClangPowerToolsShared/Resources/[CPT]GenerateDocumentation.png
  ClangPowerTools/ClangPowerToolsShared/Script/PowerShellWrapper.cs
  ClangPowerTools/ClangPowerToolsShared/Script/ScriptConstants.cs
  ClangPowerTools/ClangPowerToolsShared/Tooling/v1/clang-build.ps1
Labels: feature

#1122 Add llvm 14.0.3
  ClangPowerTools/ClangPowerTools.aip
  ClangPowerTools/ClangPowerTools/ClangPowerTools.csproj
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  ClangPowerTools/ClangPowerToolsShared/Executables/clang-format.exe
  ClangPowerTools/ClangPowerToolsShared/MVVM/Constants/LLVMVersionsAlternate.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/Constants/LlvmVersions.cs
  ClangPowerTools/ClangPowerToolsShared/Tooling/v1/psClang/get-llvm-helper.ps1
Labels: bug, enhancement

#1123 Release v8.6.0
  ClangPowerTools/ClangPowerTools.aip
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  ClangPowerTools/ClangPowerToolsShared/MVVM/Views/ReleaseNotesView.xaml
Labels: bug, enhancement

#1125 Refactoring
  ClangPowerTools/ClangPowerToolsShared/Commands/CommandController.cs
  ClangPowerTools/ClangPowerToolsShared/Helpers/GenerateDocumentation.cs
  ClangPowerTools/ClangPowerToolsShared/Output/OutputWindowConstants.cs
  ClangPowerTools/ClangPowerToolsShared/Output/OutputWindowController.cs
Labels: refactor

#1126 Download css for clang doc
  ClangPowerTools/ClangPowerToolsShared/Tooling/v1/psClang/get-llvm-helper.ps1
Labels: feature

#1128 Add tidy fix option
  ClangPowerTools/ClangPowerTools/ClangPowerTools.vsct
  ClangPowerTools/ClangPowerToolsShared/Commands/CommandController.cs
  ClangPowerTools/ClangPowerToolsShared/Commands/TidyCommand.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/Models/TidySettingsModel.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/SettingsTooltips.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/ViewModels/TidySettingsViewModel.cs
  ClangPowerTools/ClangPowerToolsShared/MVVM/Views/TidySettingsView.xaml
  ClangPowerTools/ClangPowerToolsShared/Output/OutputWindowController.cs
Labels: enhancement

#1130 Release v8.7.0
  ClangPowerTools/ClangPowerTools.aip
  ClangPowerTools/ClangPowerTools/source.extension.vsixmanifest
  ClangPowerTools/ClangPowerToolsShared/MVVM/Views/ReleaseNotesView.xaml
Labels: release

#1133 Update cpplatest flag to c++2b for LLVM 13 and newer
  ClangPowerTools/ClangPowerToolsShared/Tooling/v1/clang-build.ps1
  ClangPowerTools/ClangPowerToolsShared/Tooling/v1/psClang/io.ps1
  ClangPowerTools/ClangPowerToolsShared/Tooling/v1/psClang/msbuild-project-data.ps1
Labels: enhancement
